package eg.alexu.eng.mobdev.gradprojdemo.model;

import android.graphics.Point;
import android.media.Image;

/**
 * Created by Paula B. Bassily on 23/01/2018.
 */
public class Entity {

    // bird, cow, or any general description
    private String classification ;

    // if this entity is somehow important in the story , it should have name e.g. Nemo
    private String name ;

    // what is this entity looks like, generated by GAN in real app
    private Image image ;


    private Point position ;
    private float rotationAngle;
    private float scale ;


}
